name: Backend EC2 Deployment

on:
  push:
    branches:
      - test-branch-for-aws

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./server

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          aws-access-key-id: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          aws-secret-access-key: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          aws-region: eu-west-2

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 35.178.28.238 >> ~/.ssh/known_hosts

      - name: Build application
        run: |
          ls
          npm install
          npm run build

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/id_rsa ec2-user@35.178.28.238 'cd /app/server && git pull && pm2 restart server'
